project_id = "gigzciepwjrwbljdnixh"

[functions.get-signed-url]
verify_jwt = true

[functions.upload-to-r2]
verify_jwt = true

[functions.translate]
verify_jwt = false

[functions.og-image]
verify_jwt = false